config/routes.rb
Rails.application.routes.draw do

  # concern :attachable do
  #   resources :attachments, only: :create
  # end
  
  resources :blogs do
    member do
      get :get_subcategory
    end
  end

  resources :categories 


  devise_for :users
  devise_scope :user do  
    get "/login", :to => "devise/sessions#new" # Add a custom sign in route for user sign in
    # get "/logout", :to => "devise/sessions#destroy" # Add a custom sing out route for user sign out
    get "/register", :to => "devise/registrations#new" # Add a Custom Route for Registrations
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  
  get 'pages/homepage'
  root to: 'pages#home'
  # get "/blogs", to: "blogs#new"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  # after_save :save_attachment 

  belongs_to :user
  has_many :blog_attachments 
  # has_many :category
  # has_many :sub_category 
  # accepts_nested_attributes_for :category,allow_destroy: true
  # accepts_nested_attributes_for :sub_category
end
  

app/models/blog_attachment.rb
class BlogAttachment < ApplicationRecord
	mount_uploaders :attachment, AttachmentUploader
	belongs_to :blog
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :sub_categories
end

app/models/sub_category.rb
class SubCategory < ApplicationRecord
	belongs_to :category
end

app/models/user.rb
class User < ApplicationRecord
  has_many :blogs
      # scope :active, lambda {where(:active => true)}
  scope :admin, lambda {where(:role => "Admin")}
  scope :user, lambda {where(:role => "User")}
      # scope :phone_num, lambda {where(:phone_num => )}

 
  after_create :send_email
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable


         def self.active
           User.where(:active => true)
         end

         def is_active?
           active 
         end

  private

    def send_email
      UserMailer.welcome_email(self.email).deliver_later          
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    # params.require(:user).permit(:name, :surname, :phone_num, :role, :active, :email, :password, :password_confirmation)
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :surname, :phone_num, :role, :active, :email, :password, :password_confirmation])
  end

  # def configure_permitted_parameters
  #   attributes = [:name, :surname,:username, :email, :avatar]
  #   devise_parameter_sanitizer.permit(:sign_up, keys: attributes)
  #   devise_parameter_sanitizer.permit(:account_update, keys: attributes)
  # end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController


	def index
		@blogs = Blog.all
	end

	def show
		@blog = Blog.find(params[:id])
	end

	def new
	  @blog = Blog.new
    @categories= Category.all   
    @sub_categories =[]  
	end

	def create      
		 @blog = current_user.blogs.new(blog_params)     
    if @blog.save          
      redirect_to root_path     
   	else
      render :new, status: :unprocessable_entity
    end
  end


  def edit
  	@blog = Blog.find(params[:id]);
  end

  def update
  	 @blog = Blog.find(params[:id])
    if @blog.update(blog_params)
      redirect_to root_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @blog = Blog.find(params[:id])
    @blog.destroy
    redirect_to root_path, status: :see_other
  end


  def get_subcategory    
    category_id = Category.where(category: params["category_id"]).first.id
    @subcategories= SubCategory.where(category_id: category_id )
    respond_to do |format|    
      format.json  { render :json =>  @subcategories }
    end
  end

  private
    def blog_params
      params.require(:blog).permit(:title, :description, :category, :sub_category)
    end 
    
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def new
   @category = Category.new
  end

 def create    
     @category = Category.new(category_params)
    if @category.save
      redirect_to root_path
      # end    
    else
      render :new, status: :unprocessable_entity
    end
  end

   private

    def category_params
      params.require(:category).permit(:category)
    end

   


end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @blogs = Blog.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/blogs/_new.html.erb
<div class="modal-header"> 
  <h4 class="modal-title" id="myModalLabel">Modal title</h4> 
</div>
 <div class="modal-body"> 
 <h1>New Blog</h1>
<%= form_for  :blog, url: blogs_path do |form| %>
<!-- <%#= form_with(model: blog, local: false) do |form| %> -->
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title, class: 'form-control' %>
  </div>

  <div>
    <%= form.label :description %><br>
    <%= form.text_area :description, class: 'form-control' %>
  </div>  

  <div>
    <%= form.label 'Category' %><br>    
    <%= form.select(:category, Category.all.collect {|qt| [ qt.category, qt.category ]}, { :include_blank => "Please Select a Type" }, class:'form-control category')%>   
  </div>  

  <%= form.label "Sub Category" %><br>  
  <div class="field" id="sub_category_field">
     <%= form.select :sub_category, @sub_categories.collect {|qt| [ qt.category, qt.category ]},  {:include_blank => "Please Select a Type" }, class:'form-control sub-category', id: "sub-category" %>
  </div>

  <div class="modal-footer">     
      <%= form.submit class: "btn btn-primary" %> 
      <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button> 
  </div>
<% end %>

<script> 
  $(document).ready(function(){
    $(".category").on('change', function(){
      alert("The new team id is: " + $(this).val()); 
      $.ajax({
      url: "/blogs/:"+ $(this).val()+ "/get_subcategory",
      type: "GET",  
      data: {category_id: $(this).val()},
      success: function(data){    
                        console.log((data));     
                        var listitems = []; 
                        $.each(data,function(key, value){ 
                          listitems += '<option value="' + value.sub_category + '">' + value.sub_category + '</option>'; 
                        }); 
                        $("#sub-category").append(listitems);
                        },
      error: function(err) {}
                  console.log("error", err);
    })
   
    }); 
  });  




</script>
</div>
  
  

app/views/blogs/_sub_category.html.erb
<%= select_tag "sub_category_id", options_from_collection_for_select(@subcategories, "id", "sub_category"), :prompt => "Select a SubCategory" %>


<%#= select_tag  :sub_category, options_from_collection_for_select(@sub_categories, :id, :sub_category ),class:'form-control sub_category', id: "sub_category" %>

app/views/blogs/create.js.erb
// $("#modal-window").find(".modal-content").html("<%= j (render 'new') %>"); 
// $("#modal-window").modal();

app/views/blogs/edit.js.erb
$("#modal-window").find(".modal-content").html("<%= escape_javascript render('new', blog: @blog) %>"); 
// $("#modal-window").modal();

app/views/blogs/new.js.erb
$("#modal-window").find(".modal-content").html("<%= escape_javascript render('new', blog: @blog) %>"); 
// $("#modal-window").modal();

app/views/categories/new.html.erb
<div class="modal-header"> 
  <h4 class="modal-title" id="myModalLabel">Ceate Category</h4> 
</div>
 <div class="modal-body"> 
 <h1>New Category </h1>
<%= form_for  :category, url: categories_path do |form| %>
<!-- <%#= form_with(model: blog, local: false) do |form| %> -->
  <div>
    <%= form.label :category %><br>
    <%= form.text_field :category, class: 'form-control' %>
  </div>

  <div>
    <%= form.label :parent_category %><br>
    <%= form.text_area :parent_category, class: 'form-control' %>
  </div>  

  
  <div class="modal-footer"> 
    
      <%= form.submit class: "btn btn-primary" %> 
      <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button> 

  </div>
<% end %>
</div>
  
  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NewFaceApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <!--  <script src="https://unpkg.com/@popperjs/core@2"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script> -->
  </head>

  <body>
   
  
  <%= render 'shared/navbar' %>
  
  <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
    <%= yield %>
    

  </body>
</html>

app/views/pages/home.html.erb
<div class="container-fluid mb-4">
  <div class="row justify-content-center">
    <div class="col-10">
      <% if user_signed_in? %>
      <%= link_to 'Create Blog', new_blog_path, {:remote => true, 'data-bs-toggle' => "modal",'data-bs-target' => '#modal-window', class: 'btn btn-primary btn-lg mb-4'} %> 
      
<!-- Model code start -->
      <div id="modal-window" class="modal hide fade" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
          <div class="modal-dialog" role="document"> 
            <div class="modal-content">
                    
            </div> 
          </div>
        </div>       
<!-- Model Code end -->

<!-- Blogs Table -->
      <h1>Blogs</h1>
      <% @blogs.each do |blog| %>
      <div style="display: inline-block;">   
        <div class="card mt-4 mx-1" style="width: 18rem;">   
          <div class="card-body">
            <h5 class="card-title"><%= blog.category %></h5>
            <h5 class="card-title"><%= blog.title %></h5>
            <h6 class="card-text"><%= blog.user.name + " " +  blog.user.surname  %></h6>
            <p class="card-text"><%= blog.description %></p>
            <%= link_to "Edit", edit_blog_path(blog),{:remote => true, 'data-bs-toggle' => "modal",'data-bs-target' => '#modal-window', class: 'btn btn-primary'}%>
            <%= link_to 'Destroy', blog, method: :delete, data: { confirm: 'Are you sure?' }, :remote => true, :class => 'btn btn-danger' %>
          </div>
        </div>
      </div>

      <% end %>

<!-- Blogs table end -->

    </div> 
  </div> 
</div>     
      

      <% else %>
          <h1>Welcome to the New Face App</h1>
          <p>You can register Yourslef here</p>
      <% end %>


    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">FaceApp</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                   <%= link_to "Home", root_path, class: "nav-link" %>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Blogs</a>
                </li>

                <% if !user_signed_in?%>
                  <li class="nav-item">
                  <%= link_to "Sign In", new_user_registration_url, :class => "nav-link" %>
                  </li>
                  <li class="nav-item">
                  <%= link_to "Login", new_user_session_url, :class => "nav-link" %>
                  </li>
                <% end %>

            </ul>
            <% if user_signed_in? %>
              <ul class="navbar-nav">
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false"> <%= current_user.name %> <%= current_user.surname %></a>
                  <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                      <%= link_to "Create Category", new_category_path,  :class => "dropdown-item" %>
                    <%= link_to "Edit Profile", edit_user_registration_path,  :class => "dropdown-item" %><%= link_to "Logout", destroy_user_session_path, :method => :delete,  :class => "dropdown-item" %>  
                  </ul>
                </li>
            <% end %>                    
                </li>
              </ul>
        </div>
    </div>
</nav>